sudo: required

branches:
    only:
        - master
services:
    - docker

env:
  global:
  - secure: Ne8R8LLDtnKzEoRLOUC4ZH7rh/jWPoTvW0w+LPbPrNhftp1zIcz7OnIZN3r82/7EkAOuj6lvo1s74lXmx4/LCswALXIwYzie+EmbkHsHFAjtdGJSVdiF1+VwN9aCwrjlNnVGTmhHvk86h+tMTokSh+5YzqF5CvzzjIl4Xh0RhK6155JUT0W1IvlnqO00xpVN0Vh+7K8Q1AOzIrhzdcwhkqB/wIStAABSnG7KBCFmPesP72C4cjJGKlOHkczujX3/ZXnG2vHCGJLrrlMBnUhCDDWLgXMqquLVW/IRl6l+Q16oimF1wR5hO6jNW3kzeSygw5JF35GHWfsqTn9cu3zB0Eoh5ZtJgWZRWp1Fdh3hzgmACw+1nBk+z4p6DZZ8KLkyiU79/A4u7WHvRDJCHyj+HxPTd3v53IwkTic6Ovh+qT/e//ELJdKyG32nTZiWRc6qiRfBtG9tZPCSTBzWfTjFE9PESkdXaFulttB3qoMx3JOH5FyPuej8dYdWpayavfjMOf/SnT22oiOHx2acsXTpfHZSdDGjXFLte/rEnIOrGq8wXzOP86rK1DQOYMuhWMI0nNmKj+zCWLfZEDPW0dY6lNuFxvBCjVqyik0gdUGQ7zBXqrZJnsXS0qIqurEKJshIr4ot+68VgsyzhcX0v3wyTDbQnVKJMWi/WvWD39lwd7I=
  - secure: Er8k+2IfeLQzR5usS+kkP+tlstI/5NyXZZWsUgZHlFRmSWyynP6dUaOdlf/qpg88vnqu1s8g31q8DDlTOWZ5lKz6A8pLPL1s6vYsx9Hf296fJkJPOUGZrIjpkeMkcwn62wV4YGgVt+vGjnBYlpgqVuET22DyPmeEhiJOKNLsLnB3WfCmSG0PEs3Ctui2+KycepO8LjHHtARpFW0SGC4RzIQNDbZevJdX8NBjFMf8rvFiaTZr9eQQh/UjKedf5VwT+MpikZQwAYCVYQ6JIj1h0Y5BKqDXNsOXnBxc/TJ7YA/dk8koeC30YELO82jQLDNZhPhaMEgl5g25Q8PnECwOyXcu9vT/py4SLpCYPqG3KUMi+JVEFJZfwDXG3vlQS0xNcMcpo873LL7aqPoqd01iv7wrw6yjNX4B0xPaw1e8uSwM47NHgjTpqXXSK6g1HpJNhyffR4HKN44HPg11l4TuQNuxQjMK5E2Gl5/k1c1HVOhF9PlfHvHUqb3iLbl7rdhJ6k/KAdBXK78cbWtLkiyCJ9p06twC8wSrwqfMnZJl1gifhtF8yj+NM+UBA4XO/1gV+5EmC33yv6vigK5tsuoTwdQ5jb0rpdS8Q2r7cw2vXHma1jckzNJbpG5u7yziJRIdG2nQBziXgEgu72AHKkPkWQy0XzEkJX/7FeSuz5yX3EU=
  - secure: FpQkKikpc1FZWINZfn27W4W0KdKSJaxi0BH6RpmOiuTZOLk+887xuWcmg8ZQUdUR2KW79Qq/77en7jLV+N9X4zhBmuONBPARbD32xzkDksZpn173ksXZQSO/EqMoU3DJ9h0NqFzVoFFAQGr5nbocxELB972rLOCPhVatws2THZA93uahwTX4jTx0sXlrFtfJzpHrrp8hMWETTLBhBZ5ahs56ije+SiA51U23QjJ24kTTHbw9ajRtJO+rNOh8M/DD1j/i2B/d5ZM1ZBaEcJE1uY8b4dnP0fVKz89HwvWnBXb7XEOflQUpXUGzevb14Xw4J+lkKUBsM8mMiSPCUxmnY2HcHTpPI7K6450DTHuBBaNgEgzszY7N/b8QCH/woRgFGXzH/tmt6ELki8YwlEdZa0z2Nr+S+KsXrBG6oJBuUEQLzoWxPo+EGD7KLEVmw6t2s+gQJJHrrnBL+7Jew/2Q2L17BJCl1m5FXAOYHijif6n9ks6+kB+FG5Bf87OoQKbKTZ8E6Z1GkEKSoyhNSO048i0FuWUSWij4ZFL70RzGkL4GrkwFPmnHSkfdk1+R3pweotmpxqNT7NOF1PXEbgERld0VUf+9Q/crzwL7M+tq88e6zR3z5QDL18E5OBUOH4uNIHyg5gbpDjREcj7TUafqg6GhdtOm3HkdM7ysiPWmZ9o=
  - COMMIT=${TRAVIS_COMMIT::8}

after_success:
    - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
    - export REPO=scalatekids/scalatekids-latex
    - export TAG=`if["$TRAVIS_BRANCH" == "master"]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
    - docker build -f Dockerfile -t $REPO:$COMMIT .
    - docker tag $REPO:$COMMIT $REPO:TAG
    - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO
